.\" Manpage for bb.
.\" Contact bruce@bruce-hill.com to correct errors or typos.
.TH man 8 "22 May 2019" "1.0" "bb man page"
.SH NAME
bb \- A bitty browser for command line file management
.SH SYNOPSIS
.B bb
[\fI-d\fR]
[\fI-s\fR]
[\fIdirectory\fR]
.SH DESCRIPTION
\fBbb\fR is a tiny TUI console application for browsing and managing files.
.SH OPTIONS
.B \-d
Print the current directory on exit.

.B \-s
Print the selected files on exit.

.B directory
Open to this directory.

.SH CONTROLS
For full details on all key bindings, press \fB?\fR from inside \fBbb\fR to get
a help menu.

.TP
.B Navigating:
Arrow keys or h/j/k/l can be used to navigate.

.TP
.B Selecting:
\fBSpace\fR is used to toggle file selection. Actions (such as copying or
deleting files) are performed on the selected files. If no files are selected,
actions are performed on the file under the cursor. The selection can be
cleared by pressing \fBEscape\fR.

.TP
.B Mouse:
Clicking on a file will select it. Double clicking will open it. Clicking on
the far left character of a file's row will toggle selection of that file.

.SH EXAMPLES
.TP
.B
bb /usr/local/
Begin browsing in /usr/local/

.TP
.B
bb -s | xargs zip archive.zip
Select some files to add to a zip archive.

.TP
.B
alias bb="cd '`/usr/local/bin/bb -d || pwd`'"
Create an alias to launch \fBbb\fR and change directory to wherever it's located
when you exit (unless you exit with Ctrl-c).

.SH AUTHOR
Bruce Hill (bruce@bruce-hill.com)
