.\" Manpage for bb.
.\" Contact bruce@bruce-hill.com to correct errors or typos.
.TH man 1 "23 Feb 2020" "0.25" "bb manual page"
.SH NAME
bb \- A bitty browser for command line file management
.SH SYNOPSIS
.B bb
[\fI-d\fR]
[\fI-s\fR]
[\fI-0\fR]
[\fI-v\fR|\fI--version\fR]
[\fI-h\fR|\fI--help\fR]
[+\fI<command>\fR]*
[[--] \fI<directory>\fR | \fI<file>\fR]
.SH DESCRIPTION
\fBbb\fR is a tiny TUI console application for browsing and managing files.
.SH OPTIONS
.B \-d
Print the current directory on exit.

.B \-s
Print the selected files on exit.

.B \-0
If printing the selected files on exit, use \fBNULL\fR-terminated strings
instead of newline-separated.

.B \-d
Print the current directory on exit.

.B \--version
Print the version and exit.

.B \--help
Print the usage and exit.

.B <command>
As soon as \fBbb\fR has launched, run the given command. See \fBbbcmd\fR(1) for
more details about \fBbb\fR commands.

.B <directory>
Open \fBbb\fR viewing this directory.

.B <file>
Open \fBbb\fR in the directory containing this file, with the cursor on it.

.SH CONTROLS
For full details on all key bindings, press \fB?\fR from inside \fBbb\fR to get
a help menu.

.TP
.B Navigating:
Arrow keys or h/j/k/l can be used to navigate.

.TP
.B Selecting:
\fBSpace\fR is used to toggle file selection. Actions (such as copying or
deleting files) are performed on the selected files. If no files are selected,
actions are performed on the file under the cursor. The selection can be
cleared by pressing \fBEscape\fR.

.TP
.B Mouse:
Clicking on a file will move the cursor to it. Double clicking will open it.
Clicking on the '*' column of a file will toggle that file's selection.
Clicking on a column's label will sort according to that column.

.SH EXAMPLES
.TP
.B
bb /usr/local/
Begin browsing in /usr/local/

.TP
.B
alias bcd='cd "$(bb -d)"'
Create an alias to launch \fBbb\fR and change directory to wherever it's located
when you exit (unless you exit with Ctrl-c).

.TP
.B
bb -s -0 | xargs -0 zip archive.zip
Select some files to add to a zip archive.

.TP
.B
bb +select: *.txt
Launch \fBbb\fR with all the .txt files in the current directory selected.

.SH "SEE ALSO"
.sp
\fBbbcmd\fR(1)

.SH AUTHOR
Bruce Hill (bruce@bruce-hill.com)
