#!/bin/sh
# This file contains the script that is run when bb launches

# Create bb data dir:
[ ! -d "$XDG_DATA_HOME/bb" ] && mkdir -p "$XDG_DATA_HOME/bb"

# Load key bindings
bbkeys

# Reload settings
[ -e "$XDG_DATA_HOME/bb/settings.sh" ] && . "$XDG_DATA_HOME/bb/settings.sh"
