#!/bin/sh
# This file contains the script that is run when bb launches

[ ! -d "$XDG_DATA_HOME/bb" ] && mkdir -p "$XDG_DATA_HOME/bb"

# Load key bindings
bbbindkeys

if [ -e "$XDG_DATA_HOME/bb/settings.sh" ]; then
    . "$XDG_DATA_HOME/bb/settings.sh"
fi
